insert into Accessories values('A1', true, true, true, null);
insert into Accessories values('A2', true, true, true, null);
insert into Accessories values('A3', true, true, true, null);
insert into Accessories values('A4', true, true, true, null);
insert into Accessories values('Aula1', true, true, true, null);
insert into Accessories values('Aula2', true, true, true, null);
insert into Accessories values('Aula3', true, true, true, null);
insert into Accessories values('Aula4', true, true, true, null);
insert into Accessories values('Aula5', true, true, true, null);
insert into Accessories values('Aula6', true, true, true, null);
insert into Accessories values('Aula7', true, true, true, null);
insert into Accessories values('Aula8', true, true, true, null);
insert into Accessories values('B1', true, true, true, 'computer');
insert into Accessories values('B2', true, true, true, 'computer');
insert into Accessories values('B3', false, true, true, 'materiale elettrico');
insert into Accessories values('B4', true, true, true, null);
insert into Accessories values('C1', true, false, false, 'computer');
insert into Accessories values('C2', true, false, true, 'computer');
insert into Accessories values('C3', true, false, true, 'computer');
insert into Accessories values('C5', true, false, false, null);
insert into Accessories values('C6', true, true, true, null);
insert into Accessories values('C7', true, true, true, null);
insert into Accessories values('C8', true, true, false, null);
insert into Accessories values('D1', false, false, false, 'biologia');
insert into Accessories values('D2', false, false, false, 'biologia');
insert into Accessories values('D3', true, false, false, 'materiale elettrico');
insert into Accessories values('D4', false, false, false, 'materiale elettrico');
insert into Accessories values('D5', false, true, false, 'biologia');
insert into Accessories values('D6', false, false, false, 'materiale elettrico');
insert into Accessories values('D7', true, false, false, 'computer');
insert into Accessories values('D8', true, false, true, 'computer');
insert into Accessories values('E1', true, true, true, null);
insert into Accessories values('E2', true, true, true, null);
insert into Accessories values('E3', true, true, true, null);
insert into Accessories values('E4', true, true, false, null);
insert into Accessories values('E5', true, false, false, null);
insert into Accessories values('E6', true, true, false, null);
insert into Accessories values('E7', true, true, false, null);
insert into Accessories values('E8', true, true, false, null);
insert into Accessories values('E9', true, true, false, null);
insert into Accessories values('E10', true, true, false, null);
insert into Accessories values('EF1', true, true, true, null);
insert into Accessories values('EF2', true, true, true, null);
insert into Accessories values('EF3', true, true, true, null);
insert into Accessories values('EF4', true, true, true, null);
insert into Accessories values('F2', true, true, true, null);
insert into Accessories values('G2', true, false, true, 'computer');
insert into Accessories values('G3', true, false, true, 'disegno');
insert into Accessories values('H2', true, false, false, 'disegno');
insert into Accessories values('H3', true, true, true, 'disegno');

select nome, capacita, blackboard, whiteboard, projector, laboratory from Classroom join Accessories A on nome=A.classroom